<a href="https://colab.research.google.com/github/AllanSoto/Challenge-encriptador/blob/master/proyecto_repoteria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy pymysql dash dash-bootstrap-components python-dotenv
import os

os.environ['DB_HOST'] = 'tu_host'
os.environ['DB_PORT'] = 'tu_puerto'
os.environ['DB_USER'] = 'tu_usuario'
os.environ['DB_PASSWORD'] = 'tu_contraseña'
os.environ['DB_NAME'] = 'tu_base_de_datos'

from google.colab import drive
drive.mount('/content/drive')

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.40)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Collecting dash
  Downloading dash-3.0.2-py3-none-any.whl.metadata (10 kB)
Collecting dash-bootstrap-components
  Downloading dash_bootstrap_components-2.0.1-py3-none-any.whl.metadata (18 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.1)
Collecting Flask<3.1,>=1.0.4 (from dash)
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting Werkzeug<3.1 (from dash)
  Downloading werkzeug-3.0.6-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Collecting retrying (from dash)
  Downloading retrying-1.3.4-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (24.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from retrying->dash) (1.17.0)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.4 MB/s eta 0:00:00
Downloading dash-3.0.2-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 31.9 MB/s eta 0:00:00
Downloading dash_bootstrap_components-2.0.1-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.5/202.5 kB 12.0 MB/s eta 0:00:00
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Downloading flask-3.0.3-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 2.4 MB/s eta 0:00:00
Downloading werkzeug-3.0.6-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 14.2 MB/s eta 0:00:00
Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Installing collected packages: Werkzeug, retrying, python-dotenv, pymysql, Flask, dash, dash-bootstrap-components
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 3.1.3
    Uninstalling Werkzeug-3.1.3:
      Successfully uninstalled Werkzeug-3.1.3
  Attempting uninstall: Flask
    Found existing installation: Flask 3.1.0
    Uninstalling Flask-3.1.0:
      Successfully uninstalled Flask-3.1.0
Successfully installed Flask-3.0.3 Werkzeug-3.0.6 dash-3.0.2 dash-bootstrap-components-2.0.1 pymysql-1.1.1 python-dotenv-1.1.0 retrying-1.3.4
Mounted at /content/drive

In [2]:
!pip install faker mysql-connector-python

Collecting faker
  Downloading faker-37.1.0-py3-none-any.whl.metadata (15 kB)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.2.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (6.0 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)
Downloading faker-37.1.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 15.8 MB/s eta 0:00:00
Downloading mysql_connector_python-9.2.0-cp311-cp311-manylinux_2_28_x86_64.whl (34.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.0/34.0 MB 25.8 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python, faker
Successfully installed faker-37.1.0 mysql-connector-python-9.2.0

In [3]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.40)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.1)

In [4]:
pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.11/dist-packages (1.1.1)

In [5]:
pip install dash dash-bootstrap-components

Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (24.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from retrying->dash) (1.17.0)

In [6]:
pip install streamlit

Collecting streamlit
  Downloading streamlit-1.44.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.4)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.13.1)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.33.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.1.31)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.24.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.44.1-py3-none-any.whl (9.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 35.9 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 54.1 MB/s eta 0:00:00
Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 6.8 MB/s eta 0:00:00
Installing collected packages: watchdog, pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.44.1 watchdog-6.0.0

In [7]:
pip install flask

Requirement already satisfied: flask in /usr/local/lib/python3.11/dist-packages (3.0.3)
Requirement already satisfied: Werkzeug>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from flask) (3.0.6)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from flask) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from flask) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from flask) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from flask) (1.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2>=3.1.2->flask) (3.0.2)

In [8]:
pip install fastapi uvicorn

Collecting fastapi
  Downloading fastapi-0.115.12-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn
  Downloading uvicorn-0.34.1-py3-none-any.whl.metadata (6.5 kB)
Collecting starlette<0.47.0,>=0.40.0 (from fastapi)
  Downloading starlette-0.46.2-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from fastapi) (2.11.2)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from fastapi) (4.13.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from uvicorn) (8.1.8)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.4.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.11/dist-packages (from starlette<0.47.0,>=0.40.0->fastapi) (4.9.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (1.3.1)
Downloading fastapi-0.115.12-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 4.9 MB/s eta 0:00:00
Downloading uvicorn-0.34.1-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 2.9 MB/s eta 0:00:00
Downloading starlette-0.46.2-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 3.5 MB/s eta 0:00:00
Installing collected packages: uvicorn, starlette, fastapi
Successfully installed fastapi-0.115.12 starlette-0.46.2 uvicorn-0.34.1

In [9]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in /usr/local/lib/python3.11/dist-packages (1.1.0)

In [10]:
!pip install sqlalchemy pymysql dash dash-bootstrap-components python-dotenv

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.40)
Requirement already satisfied: pymysql in /usr/local/lib/python3.11/dist-packages (1.1.1)
Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.11/dist-packages (1.1.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (24.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from retrying->dash) (1.17.0)

In [11]:
import os

os.environ['DB_HOST'] = 'tu_host'
os.environ['DB_PORT'] = 'tu_puerto'
os.environ['DB_USER'] = 'tu_usuario'
os.environ['DB_PASSWORD'] = 'tu_contraseña'
os.environ['DB_NAME'] = 'tu_base_de_datos'

In [12]:
mode='external'

In [13]:
!pip install faker mysql-connector-python

Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (37.1.0)
Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.11/dist-packages (9.2.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)

In [14]:
!pip install faker mysql-connector-python

Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (37.1.0)
Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.11/dist-packages (9.2.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)

In [15]:
import random
from faker import Faker
import mysql.connector
from datetime import date
import calendar

In [16]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (37.1.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)

In [17]:
import sqlite3
from faker import Faker
import random
from datetime import date

# Conectar a SQLite (en memoria, también podés usar archivo si querés persistencia)
conn = sqlite3.connect('cobranzas.db')
cursor = conn.cursor()

# Borrar tabla si existe
cursor.execute("DROP TABLE IF EXISTS clientes")

# Crear la tabla
cursor.execute("""
CREATE TABLE clientes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT,
  proyecto TEXT,
  categoria TEXT,
  subcategoria TEXT,
  mora_dias INTEGER,
  deuda REAL,
  recupero REAL,
  promesa_pago REAL,
  fecha_registro DATE,
  estado TEXT
)
""")

# Preparar generador
fake = Faker('es_ES')

proyectos = [f'Proyecto {i}' for i in range(1, 6)]
categorias = {
    'Telecomunicaciones': ['Claro', 'Movistar', 'Telecable'],
    'Bancos': ['Scotiabank', 'Daviviena']
}

años = [2022, 2023, 2024, 2025]
registros_por_año = 250

# Insertar 1000 registros
for año in años:
    for i in range(registros_por_año):
        mes = random.randint(1, 4) if año == 2025 else random.randint(1, 12)
        dia = random.randint(1, 28)
        fecha_registro = date(año, mes, dia)

        nombre = fake.name()
        proyecto = random.choice(proyectos)
        categoria = random.choice(list(categorias.keys()))
        subcategoria = random.choice(categorias[categoria])
        mora_dias = random.randint(1, 89) if i < int(0.20 * registros_por_año) else random.randint(181, 365)
        deuda = round(random.uniform(100.0, 5000.0), 2)
        recupero = round(random.uniform(0, deuda), 2)
        promesa_pago = round(random.uniform(0, deuda), 2)
        estado = 'Administrativa' if mora_dias < 90 else 'Incobrable'

        cursor.execute("""
            INSERT INTO clientes (nombre, proyecto, categoria, subcategoria, mora_dias, deuda, recupero, promesa_pago, fecha_registro, estado)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (nombre, proyecto, categoria, subcategoria, mora_dias, deuda, recupero, promesa_pago, fecha_registro, estado))

conn.commit()
print("✅ Base de datos SQLite con 1000 registros creada con éxito.")

✅ Base de datos SQLite con 1000 registros creada con éxito.

In [18]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM clientes LIMIT 1000", conn)
df

,id,nombre,proyecto,categoria,subcategoria,mora_dias,deuda,recupero,promesa_pago,fecha_registro,estado
0,1,Javiera Lucena Chaparro,Proyecto 5,Bancos,Scotiabank,83,2539.91,228.58,1014.72,2022-01-17,Administrativa
1,2,Venceslás Ruano,Proyecto 5,Bancos,Scotiabank,54,1737.63,335.39,816.02,2022-01-03,Administrativa
2,3,Régulo del Blazquez,Proyecto 1,Bancos,Daviviena,26,211.03,116.10,67.70,2022-03-11,Administrativa
3,4,Samuel Perelló-Larrañaga,Proyecto 1,Telecomunicaciones,Telecable,44,1490.74,374.28,1419.01,2022-03-21,Administrativa
4,5,Julie Ferrera Carvajal,Proyecto 5,Telecomunicaciones,Claro,1,845.61,790.62,796.83,2022-03-23,Administrativa
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Evelia Barceló Carrera,Proyecto 5,Bancos,Scotiabank,267,273.70,96.96,9.44,2025-03-11,Incobrable
996,997,Remigio Javier Corral Huertas,Proyecto 1,Bancos,Daviviena,336,2051.58,426.44,873.03,2025-01-01,Incobrable
997,998,Bernarda Salazar Vidal,Proyecto 4,Bancos,Scotiabank,314,1004.60,25.45,788.15,2025-03-08,Incobrable
998,999,Lina Castelló Reig,Proyecto 3,Telecomunicaciones,Movistar,335,3887.50,1408.62,46.00,2025-01-17,Incobrable
999,1000,Pepita Arévalo-Martinez,Proyecto 4,Bancos,Daviviena,258,2019.25,1446.81,242.50,2025-03-09,Incobrable

In [19]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1DO5NxVpRDwCfGcr0gKrz6pDIvzikMfJCIZTkreLqPOI/edit#gid=0

In [20]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1r8kmJy9q-6tVMK8ko4rCoHDzo4yQai_eZ5EYf3sbaGY/edit#gid=0

In [21]:
!pip install dash dash-bootstrap-components plotly pandas

Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly) (24.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)

In [22]:
!pip install jupyter-dash dash dash-bootstrap-components plotly pandas faker

Collecting jupyter-dash
  Downloading jupyter_dash-0.4.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (37.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from jupyter-dash) (2.32.3)
Requirement already satisfied: flask in /usr/local/lib/python3.11/dist-packages (from jupyter-dash) (3.0.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from jupyter-dash) (1.3.4)
Requirement already satisfied: ipython in /usr/local/lib/python3.11/dist-packages (from jupyter-dash) (7.34.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.11/dist-packages (from jupyter-dash) (6.17.1)
Collecting ansi2html (from jupyter-dash)
  Downloading ansi2html-1.9.2-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from jupyter-dash) (1.6.0)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly) (24.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from flask->jupyter-dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from flask->jupyter-dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from flask->jupyter-dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from flask->jupyter-dash) (1.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (1.8.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (6.1.12)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (0.1.7)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (24.0.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (6.4.2)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from ipykernel->jupyter-dash) (5.7.1)
Collecting jedi>=0.16 (from ipython->jupyter-dash)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipython->jupyter-dash) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython->jupyter-dash) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython->jupyter-dash) (3.0.50)
Requirement already satisfied: pygments in /usr/local/lib/python3.11/dist-packages (from ipython->jupyter-dash) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython->jupyter-dash) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython->jupyter-dash) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->jupyter-dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->jupyter-dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->jupyter-dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->jupyter-dash) (2025.1.31)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi>=0.16->ipython->jupyter-dash) (0.8.4)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash) (5.7.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.11/dist-packages (from pexpect>4.3->ipython->jupyter-dash) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter-dash) (0.2.13)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from jupyter-core>=4.6.0->jupyter-client>=6.1.12->ipykernel->jupyter-dash) (4.3.7)
Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Downloading ansi2html-1.9.2-py3-none-any.whl (17 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.7 MB/s eta 0:00:00
Installing collected packages: jedi, ansi2html, jupyter-dash
Successfully installed ansi2html-1.9.2 jedi-0.19.2 jupyter-dash-0.4.2

In [23]:
!pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-7.2.3-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.11/dist-packages (from pyngrok) (6.0.2)
Downloading pyngrok-7.2.3-py3-none-any.whl (23 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.2.3

In [24]:
!pip install dash pyngrok pandas plotly

Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.11/dist-packages (7.2.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.11/dist-packages (from pyngrok) (6.0.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly) (24.2)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)

In [25]:
from pyngrok import ngrok

# Reemplaza con tu token real
ngrok.set_auth_token("2vgkAdqK5LMidWrmW9DIqHzBgWh_5M5QftoWLqRHg9z6xWqX9")

In [26]:
from dash import Dash, dcc, html
from pyngrok import ngrok
import pandas as pd
import plotly.express as px

In [27]:
ngrok.set_auth_token("2vgkAdqK5LMidWrmW9DIqHzBgWh_5M5QftoWLqRHg9z6xWqX9")  # ⚠️ Cámbialo por el token de tu cuenta de ngrok

In [28]:
# Crear una app Dash
app = Dash(__name__)

# Simular algunos datos (luego puedes conectar SQLite aquí)
df = pd.DataFrame({
    "Proyecto": ["Proyecto 1", "Proyecto 2", "Proyecto 3", "Proyecto 4"],
    "Recupero": [25000, 15000, 34000, 19000],
    "Promesas": [5000, 6000, 3000, 7000],
})

# Layout de la app
app.layout = html.Div([
    html.H1("Dashboard de Cobranzas", style={"textAlign": "center"}),
    dcc.Graph(figure=px.bar(df, x="Proyecto", y=["Recupero", "Promesas"], barmode="group"))
])

In [29]:
print(app)

<dash.dash.Dash object at 0x79e97327d990>

In [30]:
import sqlite3
import pandas as pd
import random
from datetime import datetime, timedelta

# Crear conexión a SQLite (en memoria o archivo)
conn = sqlite3.connect("clientes.db")  # Usa un archivo físico si quieres persistencia
cursor = conn.cursor()

# Borrar tabla si existe
cursor.execute("DROP TABLE IF EXISTS clientes")

# Crear tabla
cursor.execute("""
CREATE TABLE clientes (
    id INTEGER PRIMARY KEY,
    nombre TEXT,
    proyecto TEXT,
    categoria TEXT,
    deuda REAL,
    recupero REAL,
    promesa REAL,
    estado TEXT,
    fecha TEXT
)
""")

# Insertar 1000 registros falsos
nombres = [f"Cliente_{i}" for i in range(1, 1001)]
proyectos = ["CLARO", "MOVISTAR", "TELECABLE", "SCOTIABANK", "DAVIVIENDA"]
categorias = {
    "CLARO": "TELECOMUNICACIONES",
    "MOVISTAR": "TELECOMUNICACIONES",
    "TELECABLE": "TELECOMUNICACIONES",
    "SCOTIABANK": "BANCOS",
    "DAVIVIENDA": "BANCOS"
}
estados = ["ADMINISTRATIVA", "INCOBRABLE"]

for i in range(1000):
    nombre = nombres[i]
    proyecto = random.choice(proyectos)
    categoria = categorias[proyecto]
    deuda = round(random.uniform(5000, 150000), 2)
    estado = "ADMINISTRATIVA" if i < 200 else "INCOBRABLE"

    # Fechas entre 2022 y 2025
    year = 2022 + (i % 4)
    month = random.randint(1, 4 if year == 2025 else 12)
    day = random.randint(1, 28)
    fecha = f"{year}-{month:02d}-{day:02d}"

    recupero = round(random.uniform(0, deuda), 2)
    promesa = round(random.uniform(0, deuda - recupero), 2)

    cursor.execute("""
        INSERT INTO clientes (nombre, proyecto, categoria, deuda, recupero, promesa, estado, fecha)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (nombre, proyecto, categoria, deuda, recupero, promesa, estado, fecha))

conn.commit()
print("Base de datos y tabla `clientes` creadas con éxito.")

Base de datos y tabla `clientes` creadas con éxito.

In [33]:
import sqlite3

# Conectar a la base de datos (se crea si no existe)
conn = sqlite3.connect('recupero.db')
cursor = conn.cursor()

# Crear la tabla 'clientes' si no existe
cursor.execute('''
CREATE TABLE IF NOT EXISTS clientes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT,
    proyecto TEXT,
    categoria TEXT,
    deuda REAL,
    recupero REAL,
    promesa REAL,
    estado TEXT,
    fecha TEXT,
    anio INTEGER,
    mes INTEGER
)
''')

# Insertar algunos datos de ejemplo, excluyendo 'id' porque es autoincremental
cursor.executemany('''
INSERT INTO clientes (nombre, proyecto, categoria, deuda, recupero, promesa, estado, fecha, anio, mes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
''', [
    ('Cliente 1', 'Proyecto A', 'Categoria 1', 1000, 800, 200, 'Activo', '2025-01-15', 2025, 1),
    ('Cliente 2', 'Proyecto B', 'Categoria 2', 2000, 1500, 500, 'Inactivo', '2025-02-20', 2025, 2),
    ('Cliente 3', 'Proyecto A', 'Categoria 1', 1500, 1000, 500, 'Activo', '2025-03-10', 2025, 3),
    ('Cliente 4', 'Proyecto C', 'Categoria 3', 1200, 600, 300, 'Activo', '2025-04-25', 2025, 4)
])

# Guardar los cambios
conn.commit()

# Verificar que los datos fueron insertados correctamente
cursor.execute("SELECT * FROM clientes LIMIT 5")
clientes_data = cursor.fetchall()
print(clientes_data)

# Cerrar la conexión
conn.close()

[(1, 'Cliente 1', 'Proyecto A', 'Categoria 1', 1000.0, 800.0, 200.0, 'Activo', '2025-01-15', 2025, 1), (2, 'Cliente 2', 'Proyecto B', 'Categoria 2', 2000.0, 1500.0, 500.0, 'Inactivo', '2025-02-20', 2025, 2), (3, 'Cliente 3', 'Proyecto A', 'Categoria 1', 1500.0, 1000.0, 500.0, 'Activo', '2025-03-10', 2025, 3), (4, 'Cliente 4', 'Proyecto C', 'Categoria 3', 1200.0, 600.0, 300.0, 'Activo', '2025-04-25', 2025, 4)]

In [34]:
import sqlite3
import pandas as pd

# Conectar a la base de datos
conn = sqlite3.connect("recupero.db")

# Leer la tabla
clientes_df = pd.read_sql_query("SELECT * FROM clientes", conn)

# Convertir fecha a datetime
clientes_df["fecha"] = pd.to_datetime(clientes_df["fecha"])
clientes_df["anio"] = clientes_df["fecha"].dt.year
clientes_df["mes"] = clientes_df["fecha"].dt.month
clientes_df["dia"] = clientes_df["fecha"].dt.day

# Agrupaciones necesarias
recupero_por_anio = clientes_df.groupby("anio")["recupero"].sum().reset_index()
promesas_por_anio = clientes_df.groupby("anio")["promesa"].sum().reset_index()

recupero_vs_promesas_mes = clientes_df.groupby(["anio", "mes"])[["recupero", "promesa"]].sum().reset_index()
recupero_vs_promesas_dia = clientes_df.groupby(["anio", "mes", "dia"])[["recupero", "promesa"]].sum().reset_index()

# Crear una columna booleana para el alcance
clientes_df["con_contacto"] = (clientes_df["recupero"] > 0) | (clientes_df["promesa"] > 0)

# Agrupar y calcular el alcance como porcentaje
alcance_base = clientes_df.groupby("anio").agg(
    clientes_totales=("id", "count"),
    clientes_contactados=("con_contacto", "sum")
).reset_index()

alcance_base["alcance_base"] = (
    alcance_base["clientes_contactados"] / alcance_base["clientes_totales"] * 100
)

In [35]:
!pip install dash
!pip install pyngrok

Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (24.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from retrying->dash) (1.17.0)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.11/dist-packages (7.2.3)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.11/dist-packages (from pyngrok) (6.0.2)

In [37]:
from pyngrok import ngrok, conf

# Cerrar túneles activos
ngrok.kill()  # Esto detiene todos los túneles activos de ngrok

# Crear un nuevo túnel
public_url = ngrok.connect(8050)
print(f"Dashboard disponible en: {public_url}")

Dashboard disponible en: NgrokTunnel: "https://20df-34-56-231-101.ngrok-free.app" -> "http://localhost:8050"

In [36]:
# Asegúrate de que esta parte se haya ejecutado
recupero_por_anio = clientes_df.groupby("anio")["recupero"].sum().reset_index()
promesas_por_anio = clientes_df.groupby("anio")["promesa"].sum().reset_index()

recupero_vs_promesas_mes = clientes_df.groupby(["anio", "mes"])[["recupero", "promesa"]].sum().reset_index()
recupero_vs_promesas_dia = clientes_df.groupby(["anio", "mes", "dia"])[["recupero", "promesa"]].sum().reset_index()

porcentaje_recupero = clientes_df.groupby("anio").apply(
    lambda x: x["recupero"].sum() / x["deuda"].sum() * 100
).reset_index(name="porcentaje_recupero")

alcance_base = clientes_df.groupby("anio").apply(
    lambda x: ((x["recupero"] > 0) | (x["promesa"] > 0)).sum() / len(x) * 100
).reset_index(name="alcance_base")

# Luego el código para graficar
import plotly.express as px

fig_recupero = px.bar(recupero_por_anio, x="anio", y="recupero", title="Recupero por Año")
fig_promesas = px.bar(promesas_por_anio, x="anio", y="promesa", title="Promesas por Año")
fig_porcentaje = px.line(porcentaje_recupero, x="anio", y="porcentaje_recupero", title="Porcentaje de Recupero")
fig_alcance = px.line(alcance_base, x="anio", y="alcance_base", title="Alcance Base de Recupero")

# Mostrar los gráficos
fig_recupero.show()
fig_promesas.show()
fig_porcentaje.show()
fig_alcance.show()

<ipython-input-36-a6aeee78cbd2>:8: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

<ipython-input-36-a6aeee78cbd2>:12: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [38]:
from dash import Dash, dcc, html
import plotly.express as px
from pyngrok import ngrok

# Crear app Dash
app = Dash(__name__)

# Ejemplo: gráfico de recuperación por año
fig_recupero = px.bar(recupero_por_anio, x="anio", y="recupero", title="Recupero por Año")
fig_promesas = px.bar(promesas_por_anio, x="anio", y="promesa", title="Promesas por Año")
fig_porcentaje = px.line(porcentaje_recupero, x="anio", y="porcentaje_recupero", title="Porcentaje de Recupero")
fig_alcance = px.line(alcance_base, x="anio", y="alcance_base", title="Alcance de Contacto (% de base)")

# Diseño de la app
app.layout = html.Div([
    html.H1("Dashboard de Recupero", style={"textAlign": "center"}),
    dcc.Graph(figure=fig_recupero),
    dcc.Graph(figure=fig_promesas),
    dcc.Graph(figure=fig_porcentaje),
    dcc.Graph(figure=fig_alcance)
])

# Crear túnel con ngrok
public_url = ngrok.connect(8050)
print(f"Tu dashboard está disponible en: {public_url}")

# Ejecutar app
app.run(port=8050)

Tu dashboard está disponible en: NgrokTunnel: "https://45ab-34-56-231-101.ngrok-free.app" -> "http://localhost:8050"

In [39]:
pip install dash dash-bootstrap-components plotly

Requirement already satisfied: dash in /usr/local/lib/python3.11/dist-packages (3.0.2)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.11/dist-packages (from dash) (3.0.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.11/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly) (24.2)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from retrying->dash) (1.17.0)

In [43]:
import dash
from dash import dcc, html
import dash_bootstrap_components as dbc
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

# ------------------------------------------------------------------------------
# 1. Preparar datos ficticios para DEMO
# ------------------------------------------------------------------------------
df_financial = pd.DataFrame({
    'Year': list(range(2010, 2016)),
    'ValuePublicAssets': [100000, 120000, 140000, 160000, 200000, 250000],
    'Property': ['NY Property', 'LA Property', 'Chicago Property', 'Houston Property', 'Phoenix Property', 'Miami Property'],
    'Mortgage': [80000, 60000, 70000, 90000, 50000, 45000],
})

df_political = pd.DataFrame({
    'Year': list(range(2010, 2016)),
    'DemocratDonations': [20, 30, 45, 55, 60, 65],
    'RepublicanDonations': [10, 15, 20, 30, 35, 40],
    'OtherDonations': [5, 8, 10, 12, 15, 18],
})

# ------------------------------------------------------------------------------
# 2. Crear figuras con Plotly
# ------------------------------------------------------------------------------
# Figura 1: Valor de Activos Públicos (línea)
fig_assets = px.line(
    df_financial,
    x='Year', y='ValuePublicAssets',
    markers=True,
    title="Value of Total Public Assets"
)
fig_assets.update_layout(
    template="plotly_dark",  # Tema oscuro
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)"
)

# Figura 2: Mortgage/Properties (barras apiladas?)
fig_mortgage = px.bar(
    df_financial,
    x='Property', y='Mortgage',
    title="Mortgage on Properties"
)
fig_mortgage.update_layout(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)"
)

# Figura 3: Políticas (barras comparativas)
df_melted = df_political.melt(id_vars='Year', var_name='Party', value_name='Amount')
fig_political = px.bar(
    df_melted, x='Year', y='Amount', color='Party',
    title="Political donations",
    barmode='group'
)
fig_political.update_layout(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)"
)

# Figura 4: Donut
fig_donut = go.Figure(
    data=[go.Pie(
        labels=["Republican", "Democrat", "Other"],
        values=[40, 60, 25],
        hole=0.5
    )]
)
fig_donut.update_layout(
    template="plotly_dark",
    title="Partisan leanings",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)"
)

# ------------------------------------------------------------------------------
# 3. Diseñar el Layout con dash_bootstrap_components
# ------------------------------------------------------------------------------
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

app.layout = dbc.Container(
    fluid=True,
    children=[
        # ENCABEZADO
        dbc.Row([
            dbc.Col(html.H2("Financial & Political Overview", className="text-light"), width=6),
        ], className="my-4"),

        # PRIMERA FILA: Tarjetas de KPIs
        dbc.Row([
            dbc.Col(dbc.Card(
                dbc.CardBody([
                    html.H4("Liens", className="card-title"),
                    html.H5("$20,000 - New York, NY Property", className="card-subtitle")
                ]), color="dark", outline=True
            ), width=3),

            dbc.Col(dbc.Card(
                dbc.CardBody([
                    html.H4("Value of Assets", className="card-title"),
                    html.H5("$250k", className="card-subtitle")
                ]), color="dark", outline=True
            ), width=3),

            dbc.Col(dbc.Card(
                dbc.CardBody([
                    html.H4("Mortgages", className="card-title"),
                    html.H5("$45k", className="card-subtitle")
                ]), color="dark", outline=True
            ), width=3),

            dbc.Col(dbc.Card(
                dbc.CardBody([
                    html.H4("Donations", className="card-title"),
                    html.H5("$667,200", className="card-subtitle")
                ]), color="dark", outline=True
            ), width=3),
        ], className="mb-4"),

        # SEGUNDA FILA: 2 Cols -> (fig_assets, fig_mortgage)
        dbc.Row([
            dbc.Col(
                dbc.Card(
                    dbc.CardBody([
                        html.H5("Value of Total Public Assets", className="card-title text-light"),
                        dcc.Graph(figure=fig_assets, config={"displayModeBar": False})
                    ]), color="dark"
                ), width=6
            ),

            dbc.Col(
                dbc.Card(
                    dbc.CardBody([
                        html.H5("Properties", className="card-title text-light"),
                        dcc.Graph(figure=fig_mortgage, config={"displayModeBar": False})
                    ]), color="dark"
                ), width=6
            ),
        ], className="mb-4"),

        # TERCERA FILA: 2 Cols -> (fig_political, fig_donut)
        dbc.Row([
            dbc.Col(
                dbc.Card(
                    dbc.CardBody([
                        html.H5("Political donations", className="card-title text-light"),
                        dcc.Graph(figure=fig_political, config={"displayModeBar": False})
                    ]), color="dark"
                ), width=8
            ),

            dbc.Col(
                dbc.Card(
                    dbc.CardBody([
                        html.H5("Partisan leanings", className="card-title text-light"),
                        dcc.Graph(figure=fig_donut, config={"displayModeBar": False})
                    ]), color="dark"
                ), width=4
            ),
        ], className="mb-4"),
    ]
)

# ------------------------------------------------------------------------------
# 4. Ejecutar la aplicación
# ------------------------------------------------------------------------------
if __name__ == '__main__':
 app.run(debug=True)

In [47]:
import sqlite3
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, dcc, html
import dash_bootstrap_components as dbc
from pyngrok import ngrok

# ------------------------------------------------------------------------------
# 1. Cargar los datos desde SQLite (asegúrate de que 'recupero.db' y la tabla 'clientes' existan)
# ------------------------------------------------------------------------------
conn = sqlite3.connect("recupero.db")
clientes_df = pd.read_sql_query("SELECT * FROM clientes", conn)
conn.close()

# Convertir 'fecha' a datetime y extraer año, mes y día
clientes_df["fecha"] = pd.to_datetime(clientes_df["fecha"])
clientes_df["anio"] = clientes_df["fecha"].dt.year
clientes_df["mes"] = clientes_df["fecha"].dt.month
clientes_df["dia"] = clientes_df["fecha"].dt.day

# ------------------------------------------------------------------------------
# 2. Calcular las métricas requeridas
# ------------------------------------------------------------------------------
# Total recuperado por año
recupero_por_anio = clientes_df.groupby("anio")["recupero"].sum().reset_index()
# Total promesas por año
promesas_por_anio = clientes_df.groupby("anio")["promesa"].sum().reset_index()

# Para la gráfica de recupero, creamos un DataFrame que muestre, para cada año,
# lo recuperado y la diferencia pendiente (total promesas - total recuperado)
df_ratio = pd.merge(recupero_por_anio, promesas_por_anio, on="anio")
df_ratio["Pendiente"] = df_ratio["promesa"] - df_ratio["recupero"]

# Transformamos a formato largo, para usarlo en un gráfico Sunburst (tipo donut)
df_long = pd.melt(
    df_ratio,
    id_vars=["anio"],
    value_vars=["recupero", "Pendiente"],
    var_name="Tipo",
    value_name="Monto"
)

# ------------------------------------------------------------------------------
# 3. Crear Gráficos con Plotly usando tema oscuro y paleta de tonos menta
# ------------------------------------------------------------------------------
# Definir paleta en tonos menta
menta_palette = ["#98FF98", "#8AE79C", "#73D389", "#5BCB75", "#44B160", "#2DA64C"]

# Gráfico Donut (Sunburst) para "Recupero Total por Año"
# Este gráfico mostrará, para cada año, la proporción de lo Recuperado y lo Pendiente (Promesas - Recupero)
fig_recupero_donut = px.sunburst(
    df_long,
    path=["anio", "Tipo"],
    values="Monto",
    color="anio",
    color_discrete_sequence=menta_palette,
    title="Recupero vs. Pendiente (de Promesas) por Año",
    template="plotly_dark"
)
# Opcional: actualizar el texto
fig_recupero_donut.update_traces(textinfo="label+percent entry")

# Gráfico de barras para "Promesas de Pago por Año"
fig_promesas = px.bar(
    promesas_por_anio,
    x="anio",
    y="promesa",
    title="Promesas de Pago por Año",
    labels={"promesa": "Monto en Promesas (₡)", "anio": "Año"},
    color="anio",
    color_discrete_sequence=menta_palette,
    template="plotly_dark"
)

# Conservamos otros gráficos (porcentaje de recupero, alcance, evolución mensual, etc.) si deseas
# Por ejemplo, un gráfico de línea para el porcentaje de recupero
porcentaje_recupero = clientes_df.groupby("anio").apply(
    lambda x: x["recupero"].sum() / x["deuda"].sum() * 100
).reset_index(name="porcentaje_recupero")

fig_porcentaje = px.line(
    porcentaje_recupero,
    x="anio",
    y="porcentaje_recupero",
    title="Porcentaje de Recupero por Año",
    template="plotly_dark",
    markers=True
)

# Tarjetas de KPI para el dashboard (utilizamos los totales calculados)
tarjeta_recupero = dbc.Card(
    dbc.CardBody([
        html.H4(f"₡{recupero_por_anio['recupero'].sum():,.2f}", className="card-title"),
        html.P("Total Recuperado", className="card-text")
    ]),
    color="info", inverse=True
)

tarjeta_promesas = dbc.Card(
    dbc.CardBody([
        html.H4(f"₡{promesas_por_anio['promesa'].sum():,.2f}", className="card-title"),
        html.P("Total Promesas de Pago", className="card-text")
    ]),
    color="secondary", inverse=True
)

tarjeta_porcentaje = dbc.Card(
    dbc.CardBody([
        html.H4(f"{porcentaje_recupero['porcentaje_recupero'].mean():.2f}%", className="card-title"),
        html.P("Porcentaje de Recupero", className="card-text")
    ]),
    color="primary", inverse=True
)

# ------------------------------------------------------------------------------
# 4. Crear el Dashboard con Dash y tema DARKLY
# ------------------------------------------------------------------------------
app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

app.layout = dbc.Container(
    fluid=True,
    children=[
        # Encabezado
        dbc.Row(
            dbc.Col(html.H1("Dashboard de Cobranzas", className="text-center text-light my-4")),
            className="mb-4"
        ),

        # Tarjetas KPI
        dbc.Row([
            dbc.Col(tarjeta_recupero, md=4),
            dbc.Col(tarjeta_promesas, md=4),
            dbc.Col(tarjeta_porcentaje, md=4)
        ], className="mb-4"),

        # Gráficos
        dbc.Row([
            dbc.Col(dcc.Graph(figure=fig_recupero_donut), md=6),
            dbc.Col(dcc.Graph(figure=fig_promesas), md=6)
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(dcc.Graph(figure=fig_porcentaje), md=12)
        ], className="mb-4")
    ]
)

# ------------------------------------------------------------------------------
# 5. Exponer y ejecutar la aplicación en Colab usando ngrok
# ------------------------------------------------------------------------------
from pyngrok import ngrok

# Cierra túneles previos para evitar el límite
ngrok.kill()

public_url = ngrok.connect(addr="8050")
print("Tu dashboard está disponible en:", public_url)

if __name__ == '__main__':
    app.run(port=8050, debug=True)

<ipython-input-47-869580a1e04c>:78: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

Tu dashboard está disponible en: NgrokTunnel: "https://8d53-34-56-231-101.ngrok-free.app" -> "http://localhost:8050"

**APARTIR DE AQUI YA NO SE USA EL SERVIDOR SE UTILIZA UN EXCEL LLAMADO DE GOOGLE DRIVE**

In [84]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [86]:
import os

# Listar archivos y carpetas en tu Drive
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if 'Libro1' in file:
            print(os.path.join(root, file))

/content/drive/MyDrive/Colab Notebooks/Libro1.csv

In [87]:
import os

# Buscar el archivo "Libro1.csv" en tu Google Drive
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if 'Libro1' in file:
            print(os.path.join(root, file))

/content/drive/MyDrive/Colab Notebooks/Libro1.csv

In [88]:
csv_path = '/content/drive/MyDrive/Colab Notebooks/Libro1.csv'
df = pd.read_csv(csv_path)
df.head()

                                                                                  id;nombre;proyecto;categoria;subcategoria;mora_dias;deuda;recupero;promesa_pago;pendiente de pago;no recuperado en promesa;fecha_registro;estado
1;Javiera Lucena Chaparro;Proyecto 5;Bancos;Sco... 91;228 58;1014 72;2311 33;786                         14;17/1/2022;Administrativa
2;Venceslás Ruano;Proyecto 5;Bancos;Scotiabank;... 63;335 39;816  02;1402 24;480                          63;3/1/2022;Administrativa
229;Graciano Rius Morcillo;Proyecto 4;Bancos;Sc... 57;442 62;440  31;479  95;-2                              31;16/3/2022;Incobrable
4;Samuel Perelló-Larrañaga;Proyecto 1;Telecomun... 74;374 28;1419 01;1116 46;1044                        73;21/3/2022;Administrativa
5;Julie Ferrera Carvajal;Proyecto 5;Telecomunic... 61;790 62;796  83;54   99;6                           21;23/3/2022;Administrativa

# ***apartir de aqui pruebas para ver el dashboard con los datos del ecxel del drive***

In [78]:
print(df.columns)

Index(['id;nombre;proyecto;categoria;subcategoria;mora_dias;deuda;recupero;promesa_pago;pendiente de pago;no recuperado en promesa;fecha_registro;estado'], dtype='object')

In [95]:
# DASHBOARD RESUELVA CR 2025

import pandas as pd
import dash
import dash_bootstrap_components as dbc
from dash import dcc, html, Input, Output
import plotly.express as px
from google.colab import drive

# Montar Google Drive
drive.mount('/content/drive')

# Ruta del archivo CSV
csv_path = '/content/drive/MyDrive/Colab Notebooks/Libro1.csv'

# Cargar datos y limpiar
columnas = ['id', 'nombre', 'proyecto', 'categoria', 'subcategoria', 'mora_dias', 'deuda',
            'recupero', 'promesa_pago', 'pendiente de pago', 'no recuperado en promesa',
            'fecha_registro', 'estado']

df = pd.read_csv(csv_path, sep=';', names=columnas, header=0)

# Limpieza de columnas numéricas
df['deuda'] = pd.to_numeric(df['deuda'], errors='coerce')
df['recupero'] = pd.to_numeric(df['recupero'], errors='coerce')
df['promesa_pago'] = pd.to_numeric(df['promesa_pago'], errors='coerce')

# Convertir fecha y desglosar

# Detectar el formato de fecha correcto automáticamente
try:
    df['fecha_registro'] = pd.to_datetime(df['fecha_registro'], dayfirst=True, errors='coerce')
except:
    df['fecha_registro'] = pd.to_datetime(df['fecha_registro'], errors='coerce')

# Extraer partes de la fecha
df['año'] = df['fecha_registro'].dt.year
df['mes'] = df['fecha_registro'].dt.month
df['dia'] = df['fecha_registro'].dt.day

# Filtrado 2025 hasta abril
df_2025 = df[(df['año'] == 2025) & (df['mes'] <= 4)]

# KPIs de 2025
recupero_2025 = df_2025['recupero'].sum()
promesas_2025 = df_2025['promesa_pago'].sum()

# Tarjetas
kpi_style = {'backgroundColor': '#1e1e1e', 'color': 'white', 'padding': '20px', 'borderRadius': '15px'}

tarjeta_recupero = dbc.Card([
    dbc.CardBody([
        html.H4("TOTAL RECUPERADO 2025", className="card-title text-success"),
        html.H2(f"\u20a11{recupero_2025:,.0f}", className="card-text")
    ])
], style=kpi_style)

tarjeta_promesas = dbc.Card([
    dbc.CardBody([
        html.H4("TOTAL PROMESAS 2025", className="card-title text-primary"),
        html.H2(f"\u20a11{promesas_2025:,.0f}", className="card-text")
    ])
], style=kpi_style)

porcentaje = (recupero_2025 / promesas_2025 * 100) if promesas_2025 > 0 else 0

tarjeta_porcentaje = dbc.Card([
    dbc.CardBody([
        html.H4("% RECUPERADO 2025", className="card-title text-info"),
        html.H2(f"{porcentaje:.2f}%", className="card-text")
    ])
], style=kpi_style)

# GRAFICAS

# Donut por subcategoría 2025
fig_recupero_donut = px.pie(df_2025, names='subcategoria', values='recupero', title='Recupero por Subcategoría 2025')
fig_recupero_donut.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Promesas por año (2022 a 2025)
df_multi = df[df['año'].isin([2022, 2023, 2024, 2025]) & (df['mes'] <= 4)]
promesas_año = df_multi.groupby('año')[['promesa_pago', 'recupero']].sum().reset_index()
fig_promesas = px.bar(promesas_año, x='año', y=['promesa_pago', 'recupero'], barmode='group', title='Promesas vs Recupero por Año')
fig_promesas.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Porcentaje de recupero diario
df_diario = df_2025.groupby('fecha_registro')[['recupero']].sum().reset_index()
fig_porcentaje = px.line(df_diario, x='fecha_registro', y='recupero', title='Recupero Diario en 2025')
fig_porcentaje.update_traces(mode="lines+markers")
fig_porcentaje.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Recupero vs Promesa por mes 2025
mensual = df_2025.groupby('mes')[['recupero', 'promesa_pago']].sum().reset_index()
fig_mes = px.bar(mensual, x='mes', y=['recupero', 'promesa_pago'], barmode='group', title='Recupero vs Promesa por Mes 2025')
fig_mes.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Recupero vs Promesa por Año
anual = df[df['año'] <= 2025].groupby('año')[['recupero', 'promesa_pago']].sum().reset_index()
fig_anual = px.bar(anual, x='año', y=['recupero', 'promesa_pago'], barmode='group', title='Recupero vs Promesa por Año')
fig_anual.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Avance en abril 2025
df_abril = df_2025[df_2025['mes'] == 4].groupby('dia')[['recupero', 'promesa_pago']].sum().reset_index()
fig_abril = px.line(df_abril, x='dia', y=['recupero', 'promesa_pago'], markers=True, title='Avance Abril 2025')
fig_abril.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Subcategoría recuperada
subcat_2025 = df_2025.groupby('subcategoria')['recupero'].sum().reset_index().sort_values(by='recupero', ascending=False)
fig_subcat = px.bar(subcat_2025, x='subcategoria', y='recupero', title='Recuperado por Subcategoría 2025')
fig_subcat.update_layout(paper_bgcolor='#1e1e1e', plot_bgcolor='#1e1e1e', font_color='white')

# Crear App con tema DARKLY
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

app.layout = dbc.Container(
    fluid=True,
    children=[
        dbc.Row(dbc.Col(html.H1("RESUELVA CR 2025", className="text-center text-light my-4"))),

        dbc.Row([
            dbc.Col(tarjeta_recupero, md=4),
            dbc.Col(tarjeta_promesas, md=4),
            dbc.Col(tarjeta_porcentaje, md=4)
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(dcc.Graph(figure=fig_recupero_donut), md=6),
            dbc.Col(dcc.Graph(figure=fig_promesas), md=6)
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(dcc.Graph(figure=fig_porcentaje), md=6),
            dbc.Col(dcc.Graph(figure=fig_mes), md=6)
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(dcc.Graph(figure=fig_anual), md=6),
            dbc.Col(dcc.Graph(figure=fig_abril), md=6)
        ], className="mb-4"),

        dbc.Row([
            dbc.Col(dcc.Graph(figure=fig_subcat), md=12)
        ])
    ]
)

# Ejecutar app (en Colab cambiar a .run(mode='inline') si necesario)
app.run(mode='inline')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).